disabled_rules:
  - cyclomatic_complexity
  - function_body_length
  - discarded_notification_center_observer
  - type_body_length
  - nesting
  - large_tuple
  - function_parameter_count
  - trailing_whitespace
  - void_return
  - closure_end_indentation
  - trailing_comma
  - todo
  - line_length
  - identifier_name
  - custom_wrong_id

opt_in_rules:
  - force_unwrapping
  - closure_end_indentation
  - sorted_imports
  - unneeded_parentheses_in_closure_argument

excluded:
  - Pods

warning_threshold: 1

line_length:
  warning: 120
  error: 120
  ignores_urls: true
  ignores_comments: true

file_length:
  warning: 1000
  error: 2000

identifier_name:
  min_length: 2
  max_length: 60

type_name:
  min_length: 2
  max_length: 60

force_unwrapping:
  error

#Будет ошибка при принудительном касте типов
force_cast:
  error

#Ошибка при точке с запятой на конце
trailing_semicolon:
  error

#Будет ошибка при излишних скобках
control_statement:
  error

#Будет ошибка при лишнем указании getter-a
implicit_getter:
  error

#Будет ошибка, если параметры метода расположены вертикально и не из одной табуляции
vertical_parameter_alignment:
  error

#Будет ошибка при отсутствии нужных пробелов при указании возвращаемого значения
return_arrow_whitespace:
  error

#Будет ошибка при лишнем упоминании неиспользуемых объектов
unused_optional_binding:
  error

#Будет ошибка при указании уточненных типов массивов и словарей в устаревших форматах
syntactic_sugar:
  error

#Кастомные правила
custom_rules:
  custom_dto_suffix:
    name: "Модель DTO должна иметь суффикс 'DTO'"
    included: "Project112/DTO"
    regex: "(struct \\w*(?<!DTO):)|(struct (\\w*(?<!DTO)<))"
    message: "Модель DTO должна иметь суффикс 'DTO'"
    severity: error

  custom_enum_suffix:
    name: "Enum в DTO запрещены"
    included: "Project112/DTO"
    regex: "(enum (?!CodingKeys))"
    message: "Используйте enum в моделях"
    severity: error

  custom_wrong_url:
    name: "Неверное наименование URL"
    excluded: "Project112/DTO"
    regex: "(var|let) \\w*Url( |:)"
    message: "Используй URL"
    severity: error
  custom_void_return:
    name: "Неверное использование Void"
    regex: "([(](Void)?[)] ?-> ?Void)"
    match_kinds:
      - typeidentifier
    message: "Используй '() -> ()'"
    severity: error

  custom_empty_string:
    name: "Неверная проверка строки на пустоту"
    regex: "( == \"\")|(== \"\")|( ==\"\")|(==\"\")|( != \"\")|(!= \"\")|( !=\"\")|(!=\"\")"
    message: "Используй 'string.isEmpty'"
    severity: error

  custom_guard_self:
    name: "Неверное использование guard let self = self"
    regex: "guard\\s+let\\s+(((?!self).)\\S* = self[ ,]|`self` = self)"
    message: "Используй 'guard let self = self'"
    severity: error

  custom_void_return:
    name: "Неверное использование Void"
    regex: "([(](Void)?[)] ?-> ?Void)"
    match_kinds:
      - typeidentifier
    message: "Используй '() -> ()'"
    severity: error

  custom_guard_self:
    name: "Неверное использование guard let self = self"
    regex: "guard\\s+let\\s+(((?!self).)\\S* = self[ ,]|`self` = self)"
    message: "Используй 'guard let self = self'"
    severity: error

  custom_types_Int:
    name: "Лишнее указание типа"
    regex: "(var|let) \\w*: Int = \\d"
    message: "Не указывай тип"
    severity: error

  custom_types_Double:
    name: "Лишнее указание типа"
    regex: "(var|let) \\w*: Double = \\d"
    message: "Не указывай тип"
    severity: error

  custom_types_Date:
    name: "Лишнее указание типа"
    regex: "(var|let) \\w*: Date = Date\\("
    message: "Не указывай тип"
    severity: error


  custom_array_Type:
    name: "Неверное создание массива"
    regex: "(var|let) \\w* = \\[\\w*\\]\\(\\)"
    message: "var a: [Type] = []"
    severity: error

  custom_boolean_redundant_condition:
    name: "Optional chaining для Bool запрещен"
    regex: "(?? true)|(?? false)"
    message: "Используй == true или == false"
    severity: error

  vboolean_clear_condition:
    name: "Переусложненное условие"
    regex: "^(?>(?!(as\\?)|(\\?.)).)*((!= true)|(!= false)).*$"
    message: "Используй == true или == false или саму перменную в качестве условия"
    severity: error

  custom_documentation_ticks:
    name: "Неверный апостроф в документации"
    regex: "´"
    message: "Используй '`' вместо '´' для корректной работы документации."
    match_kinds:
      - comment
      - doccomment
    severity: error

  custom_boolean_in_ternar_return:
    name: "Возврат Bool из тернарного оператора"
    regex: "\\? (true : false)|(false : true)"
    message: "Не используй тернарный оператор для возврата Bool"
    severity: error

  custom_unowned:
    name: "Использование unowned"
    regex: "\\[unowned "
    message: "Используй 'weak' вместо 'unowned'"
    severity: error

  custom_type_inferred_context:
    name: "Лишнее указание типа"
    regex: "^\\w* *((var)|(let)) \\w+\\:\\s(\\w+)\\s\\=\\s\\4"
    message: "var a = Class()"
    severity: error

  custom_type_inferred_context2:
    name: "Лишнее указание типа"
    regex: "^(?>(?!(\\w* *((var)|(let)) \\w+))).*: (\\w+) = \\5\\.(\\w+)(?>(?!\\(\\)))"
    message: "func f(a: UIColor = .red)"
    severity: error

  custom_func_line_breaks:
    name: "Переносы при вызове функции"
    regex: "\\w+\\((\\w+: |)[\\w.|\\[\\]\":$%]+,$"
    message: "Переносы строк необходимо делать по гайду"
    severity: error

  custom_array_line_breaks:
    name: "Переносы при многострочных массивах"
    regex: "\\[[\\d\\w,.]+,$"
    message: "Переносы строк для многострочных массивов необходимо делать по гайду"
    severity: error

  custom_custom_void_handler:
    name: "Используй VoidHandler"
    regex: "typealias \\w+ = (VoidHandler|\\( *\\) *-> *\\( *\\))"
    message: "Вместо кастомного typealias используй VoidHandler"
    severity: error

  custom_error_handler:
    name: "Используй ErrorHandler"
    regex: "\\(NSError\\) *-> *\\( *\\)"
    message: "Вместо (NSError) -> () используй ErrorHandler"
    severity: error

  custom_custom_error_handler:
    name: "Используй ErrorHandler"
    regex: "typealias \\w+ = (ErrorHandler|\\(NSError\\) *-> *\\( *\\))"
    message: "Вместо кастомного typealias используй ErrorHandler"
    severity: error

  custom_optional_error_handler:
    name: "Используй OptionalErrorHandler"
    regex: "\\(NSError\\?\\) *-> *\\( *\\)"
    message: "Вместо (NSError?) -> () используй OptionalErrorHandler"
    severity: error

  custom_custom_optional_error_handler:
    name: "Используй OptionalErrorHandler"
    regex: "typealias \\w+ = (OptionalErrorHandler|\\(NSError\\?\\) *-> *\\( *\\))"
    message: "Вместо кастомного typealias используй OptionalErrorHandler"
    severity: error

  custom_int_handler:
    name: "Используй IntHandler"
    regex: "\\(Int\\) *-> *\\( *\\)"
    message: "Вместо (Int) -> () используй IntHandler"
    severity: error

  custom_custom_int_handler:
    name: "Используй IntHandler"
    regex: "typealias \\w+ = (IntHandler|\\(Int\\) *-> *\\( *\\))"
    message: "Вместо кастомного typealias используй IntHandler"
    severity: error

  custom_bool_handler:
    name: "Используй BoolHandler"
    regex: "\\(Bool\\) *-> *\\( *\\)"
    message: "Вместо (Bool) -> () используй BoolHandler"
    severity: error

  custom_custom_bool_handler:
    name: "Используй BoolHandler"
    regex: "typealias \\w+ = (BoolHandler|\\(Bool\\) *-> *\\( *\\))"
    message: "Вместо кастомного typealias используй BoolHandler"
    severity: error

  custom_string_handler:
    name: "Используй StringHandler"
    regex: "\\(String\\) *-> *\\( *\\)"
    message: "Вместо (String) -> () используй StringHandler"
    severity: error

  custom_custom_string_handler:
    name: "Используй StringHandler"
    regex: "typealias \\w+ = (StringHandler|\\(String\\) *-> *\\( *\\))"
    message: "Вместо кастомного typealias используй StringHandler"
    severity: error

  custom_handler_names:
    name: "Нейменг блоков"
    regex: "(var|let) \\w+(Action|Block): (\\(|\\w+(Handler|Action|Handler))"
    message: "Замыкание должно иметь суффикс Handler"
    severity: error

  custom_forced_handlers:
    name: "Force unwrap для замыканий запрещен"
    regex: "(var|let) \\w+: (\\(*\\w*\\)->\\(\\w*\\)*|\\w+(Handler|Action|Handler))!"
    message: "Вместо var handler: Handler! используй var handler: Handler?"
    severity: error

  custom_color_literal:
    name: "Используй готовые цвета"
    regex: "#colorLiteral"
    message: "Существующие цвета можно посмотреть в UIKitApp или в UIColor+Colors.swift. Если цвет новый, то стоит его занести в HEX формате (после согласования с Core-командой)"
    severity: error

  custom_add_subviews:
    name: "Внутри 'addSubviews()' запрещено использование 'addSubview()'"
    regex: "addSubviews\\(\\) \\{\\n\\s*\\w*.addSubview\\("
    message: "Используй 'add {}' в декларативном стиле"
    severity: error

  custom_objc_inline:
    name: "Неверное написание @objc"
    regex: "@objc\\n"
    message: "Пиши @objc в одну строку"
    severity: error

  custom_texts:
    name: "Использовать хардкод для текста в Presentation запрещено"
    included: "Project112/Presentation"
    regex: "\"[a-zA-Zа-яА-Я]"
    message: "Используйте структуру Texts"
    match_kinds:
      - string
    severity: error

  custom_doc:
    name: "Отсутствует документация на неприватный интерфейс двумя строками ниже"
    regex: "\\n\\n(public|open|struct|class|enum) (?!\\w+_Previews)"
    message: "Добавьте документацию через комбинацию клавиш CMD+OPTION+/"
    severity: error
